/// What produced an [Expense], when it wasn't the user typing it in.
///
/// Stored on the expense as `sourceType` alongside a `sourceId` pointing at
/// the doc that generated it. Same shape as [IncomeSource] (a string `value`
/// persisted verbatim), but with one deliberate difference: [fromValue]
/// returns `null` for an unrecognized value instead of falling back to a
/// catch-all member. A value this build doesn't know about is a source added
/// by a NEWER build; degrading it to "manual" in the UI is honest (we can't
/// say what made it), whereas mapping it onto some existing member would be a
/// lie about which subscription/purchase it came from.
enum ExpenseSource {
  /// Generated by `FirestoreService.catchUpSubscriptions`; `sourceId` is the
  /// `subscriptions/{id}` doc.
  subscription('subscription'),

  /// Generated by `FirestoreService.catchUpInstallmentPurchases`; `sourceId`
  /// is the `installmentPurchases/{id}` doc.
  installment('installment');

  final String value;
  const ExpenseSource(this.value);

  /// `null` for null/unknown input — see the class doc for why there is no
  /// catch-all fallback.
  static ExpenseSource? fromValue(String? value) {
    if (value == null) return null;
    for (final source in ExpenseSource.values) {
      if (source.value == value) return source;
    }
    return null;
  }
}
