import 'expense_source.dart';

/// Mirrors `ExpenseSchema` in the Next.js app's `src/lib/schemas.ts`.
/// [categoryId] is nullable — null means the expense came straight out of
/// the general account balance instead of a caixinha.
///
/// [sourceType]/[sourceId] are null for an expense the user typed in, and set
/// together for one generated by a recurring charge (see
/// `FirestoreService.catchUpSubscriptions` /
/// `catchUpInstallmentPurchases`). They're the same "pair the rows by an id"
/// idea as `Allocation.transferId`: without them a generated expense is
/// indistinguishable from a manual one with the same description, so the app
/// can't tell you what a subscription has actually cost you so far, and can't
/// tell that you deleted a charge by hand. Both are optional fields added
/// after the original schema, so an older JSON backup imports unchanged.
class Expense {
  final String id;
  final String date; // ISO date string (YYYY-MM-DD)
  final double amount;
  final String? categoryId;
  final String? description;

  /// Raw stored value of the generating source's kind — deliberately a String
  /// and not an [ExpenseSource], so a value written by a newer build (a
  /// source kind this build doesn't know yet) survives a
  /// fetch -> backup -> restore round trip instead of being silently dropped
  /// on the way back out. Read it through [source] for the typed view.
  final String? sourceType;

  /// Id of the doc that generated this expense (a `subscriptions/{id}` or
  /// `installmentPurchases/{id}`). Set together with [sourceType]; the doc it
  /// points at may since have been deleted, so treat it as a label, not a
  /// guaranteed reference.
  final String? sourceId;

  const Expense({
    required this.id,
    required this.date,
    required this.amount,
    this.categoryId,
    this.description,
    this.sourceType,
    this.sourceId,
  });

  /// Typed view of [sourceType]; null when this expense was entered by hand
  /// OR when [sourceType] holds a kind this build doesn't recognize.
  ExpenseSource? get source => ExpenseSource.fromValue(sourceType);

  /// Whether a recurring charge produced this expense rather than the user.
  bool get isGenerated => sourceId != null;

  factory Expense.fromMap(String id, Map<String, dynamic> map) {
    return Expense(
      id: id,
      date: map['date'] as String,
      amount: (map['amount'] as num).toDouble(),
      categoryId: map['categoryId'] as String?,
      description: map['description'] as String?,
      sourceType: map['sourceType'] as String?,
      sourceId: map['sourceId'] as String?,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'date': date,
      'amount': amount,
      if (categoryId != null) 'categoryId': categoryId,
      if (description != null) 'description': description,
      if (sourceType != null) 'sourceType': sourceType,
      if (sourceId != null) 'sourceId': sourceId,
    };
  }

  factory Expense.fromJson(Map<String, dynamic> json) {
    return Expense.fromMap(json['id'] as String, json);
  }

  Map<String, dynamic> toJson() => {'id': id, ...toMap()};
}
