// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAuNG25a2fT9l_mYVxPUtq2TUPa-QzQwA',
    appId: '1:368601445760:web:207d40c10e9774e1b5fd65',
    messagingSenderId: '368601445760',
    projectId: 'dindin-cafelabs',
    authDomain: 'dindin-cafelabs.firebaseapp.com',
    storageBucket: 'dindin-cafelabs.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOh6SKVJQyJju9Oc6tDGcs0rFrhFch8aE',
    appId: '1:368601445760:android:8daf38873eb6df02b5fd65',
    messagingSenderId: '368601445760',
    projectId: 'dindin-cafelabs',
    storageBucket: 'dindin-cafelabs.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAuNG25a2fT9l_mYVxPUtq2TUPa-QzQwA',
    appId: '1:368601445760:web:2f4f902da94cced5b5fd65',
    messagingSenderId: '368601445760',
    projectId: 'dindin-cafelabs',
    authDomain: 'dindin-cafelabs.firebaseapp.com',
    storageBucket: 'dindin-cafelabs.firebasestorage.app',
  );
}
